#! /usr/bin/env python

import cgitb
cgitb.enable()

import os, sys, json, traceback, hashlib, binascii


def generateSwype(blockHash, account):
    global config
    modulo=config["swypeModulo"]

    digest=hashlib.sha256(binascii.a2b_hex(blockHash[2:]+account[2:])).digest()

    swypeid=0
    for c in digest:
        if type(c)!=int:
            c=ord(c)
        swypeid=(swypeid*256+c)%modulo

    seq=[5]   # always start from the center
    n=swypeid
    m=1
    while m<modulo:
        # 1 2 3
        # 4 5 6
        # 7 8 9
        neighbours=[
            [2, 4, 5],
            [1, 3, 4, 5, 6],
            [2, 5, 6],
            [1, 2, 5, 7, 8],
            [1, 2, 3, 4, 6, 7, 8, 9],
            [2, 3, 5, 8, 9],
            [4, 5, 8],
            [4, 5, 6, 7, 9],
            [5, 6, 8]
        ]
        curpt=seq[-1]
        nc=len(neighbours[curpt-1])
        nextpt=neighbours[curpt-1][n*nc//modulo]

        m*=nc
        n=(n*nc)%modulo

        seq.append(nextpt)

    return {"swype-id":swypeid, "swype-sequence":seq}

# Python 2/3 compatibility stuff
if str==bytes:
    from urlparse import parse_qs, parse_qsl
    from urllib import urlencode
    from urllib2 import urlopen
    from urllib2 import Request
else:
    from urllib.parse import parse_qs, parse_qsl
    from urllib.parse import urlencode
    from urllib.request import urlopen
    from urllib.request import Request
    sys.stdout=sys.stdout.buffer
    sys.stdin=sys.stdin.buffer


configfile=os.getenv("PROVER_MVP_CONFIG", "/etc/prover/prover.conf")
try:
    config=json.load(open(configfile, "rt"))
except:
    sys.stdout.write(b"Status: 500 Internal Server Error\n\nServer is not configured properly\n")
    sys.exit(0)

try:
    if os.environ["REQUEST_METHOD"]!="POST":
        sys.stdout.write(b"Status: 405 Method Not Allowed\n\nOnly POST method is allowed\n")
        sys.exit(0)

    if os.environ["CONTENT_TYPE"]!="application/x-www-form-urlencoded":
        sys.stdout.write(b"Status: 415 Unsupported Media Type\n\nOnly x-www-form-urlencoded content type is supported\n")
        sys.exit(0)

    data=sys.stdin.read().decode("latin1")
    query_args=parse_qs(data, keep_blank_values=True)
except Exception:
    sys.stdout.write(b"Status: 500 Internal Server Error\n\n"+traceback.format_exc().encode("utf8")+b"\n")
    sys.exit(0)

if "user" in query_args:
    user=query_args["user"][0]

    rpcrequest={"jsonrpc":"2.0", "method":"eth_blockNumber", "params":[], "id":0}

    request=Request("http://"+config["node"], data=json.dumps(rpcrequest).encode("latin1"), headers={"Content-Type": "application/json"})
    reply=urlopen(request)
    if reply.getcode()!=200:
        sys.stdout.write(b"Status: 500 Internal Server Error\n\nNode error\n")
        sys.exit(0)

    topBlock=int(json.loads(reply.read().decode("latin1"))["result"], 16)

    rpcrequest={"jsonrpc":"2.0", "method":"eth_getBlockByNumber", "params":["0x{0:x}".format(topBlock-2), False], "id":0}

    request=Request("http://"+config["node"], data=json.dumps(rpcrequest).encode("latin1"), headers={"Content-Type": "application/json"})
    reply=urlopen(request)
    if reply.getcode()!=200:
        sys.stdout.write(b"Status: 500 Internal Server Error\n\nNode error\n")
        sys.exit(0)

    blockHash=json.loads(reply.read().decode("latin1"))["result"]["hash"]

    swype=generateSwype(blockHash, user)

    res={"result": swype}
    res["result"]["reference-block"]=blockHash

    sys.stdout.write(b"Status: 200 OK\nContent-Type: application/json\n\n"+json.dumps(res).encode("latin1")+b"\n")

else:
    sys.stdout.write(b"Status: 400 Bad Request\n\n")
